fix: add check-directives to CI

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -21,8 +21,30 @@ on:
       - "docs/*"
 
 jobs:
+  check-directives:
+    name: Check Preprocessor Directives
+    runs-on: ubuntu-latest
+    env:
+      HEADER_FILE: src/NetWizard.h
+    steps:
+      - name: Checkout Repository
+        uses: actions/checkout@v4
+      - name: Check NETWIZARD_USE_ASYNC_WEBSERVER
+        env:
+          DIRECTIVE: NETWIZARD_USE_ASYNC_WEBSERVER
+          EXPECTED_VALUE: 0
+        run: |
+          if [ ! -f "$HEADER_FILE" ]; then
+            echo "$HEADER_FILE not found!" && exit 1
+          fi
+          if ! grep -Eq "#define[[:space:]]+$DIRECTIVE[[:space:]]+$EXPECTED_VALUE([[:space:]]+|$)" "$HEADER_FILE"; then
+            echo "$DIRECTIVE is not set to $EXPECTED_VALUE!" && exit 1
+          fi
+          echo "Preprocessor directive is correctly set to $EXPECTED_VALUE."
+
   arduino:
     name: Arduino - ${{ matrix.name }}
+    needs: check-directives
     runs-on: ubuntu-latest
     strategy:
       fail-fast: false
@@ -106,6 +128,7 @@ jobs:
 
   platformio:
     name: PlatformIO - ${{ matrix.name }}
+    needs: check-directives
     runs-on: ubuntu-latest
     strategy:
       fail-fast: false
